### ISSUE TITLE
找了半天，才找到这个，多谢。但是这个在移动端还是有点BUG

### ISSUE THREAD

**Issue by EnkeChan** [WittBulter/taobaoScroller#1]
在手机UC（IOS和安卓），小米原生浏览器上，安卓chrome都打无法上拉。这是怎么回事啊，Safari没问题

**Comment by WittBulter** [comment]
对于UC浏览器未能兼容，抱歉。
这个项目是我帮助一位朋友写的业务功能，代码不是非常友好，如果你希望能够有不错的兼容性，可以看源码自己进行修改。

**Comment by EnkeChan** [comment]
没事。多谢
